name: seban_board
description: "A Flutter-Based Kanban Board with a Twist."
publish_to: "none"
version: 0.4.1+1

environment:
    sdk: ^3.11.3

dependencies:
    desktop_multi_window: ^0.3.1
    drag_and_drop_lists: ^0.4.2
    file_picker: ^12.2.0
    flutter:
        sdk: flutter
    path_provider: ^2.1.6
    window_manager: ^0.5.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    uses-material-design: true
